"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { BrainCircuit, Activity, Pill, Stethoscope, CheckCircle2, AlertTriangle, ShieldCheck, Zap, Loader2, RefreshCw } from "lucide-react";
import { fetchAiSummary, resolveActivePatient } from "@/lib/api";
import { MedicalDisclaimer } from "@/components/Brand";

type AiSummaryData = {
  patient_name: string;
  executive_summary: string;
  key_diagnoses: string[];
  active_medications_summary: Array<{ name: string; dosage_notes: string; status: string }>;
  lab_overview: Array<{ test_name: string; latest_finding: string; status: string }>;
  clinical_recommendations: string[];
  confidence_score: number;
  medical_disclaimer: string;
};

export default function AiSummaryPage() {
  const [summaryData, setSummaryData] = useState<AiSummaryData | null>(null);
  const [patientName, setPatientName] = useState<string | undefined>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadSummary = async () => {
    try {
      setLoading(true);
      setError(null);
      const active = await resolveActivePatient();
      setPatientName(active);
      const data = await fetchAiSummary(active);
      setSummaryData(data);
    } catch (err: any) {
      console.error("Failed to fetch AI Summary:", err);
      setError(err.message || "Failed to load AI Medical Summary.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSummary();
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] space-y-4">
        <Loader2 className="w-8 h-8 text-brand-500 animate-spin" />
        <p className="text-slate-500 font-medium">Generating Groq AI Medical Summary...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8 max-w-4xl mx-auto">
        <div className="bg-rose-50 border border-rose-200 text-rose-700 p-6 rounded-xl flex items-start gap-4">
          <AlertTriangle className="w-6 h-6 shrink-0 mt-0.5" />
          <div>
            <h3 className="font-bold text-lg">Error loading summary</h3>
            <p className="mt-1">{error}</p>
            <button
              onClick={loadSummary}
              className="mt-4 inline-flex items-center gap-2 bg-slate-800 text-white px-4 py-2 rounded-xl text-xs font-semibold hover:bg-slate-900"
            >
              <RefreshCw className="w-3.5 h-3.5" /> Retry
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!summaryData) return null;

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-800 flex items-center gap-3">
            <BrainCircuit className="w-8 h-8 text-brand-600" />
            AI Executive Summary {patientName ? `— ${patientName}` : ""}
          </h1>
          <p className="text-slate-500 mt-1">
            Real-time synthesis of all medical records generated by Groq (llama-3.3-70b-versatile).
          </p>
        </div>

        <div className="flex items-center gap-2 bg-white border border-slate-200 px-4 py-2 rounded-2xl shadow-sm w-fit">
          <Zap className="w-4 h-4 text-emerald-500" />
          <span className="text-xs font-bold text-slate-700">
            {summaryData.confidence_score}% AI Confidence
          </span>
        </div>
      </div>

      {/* Executive Summary Hero Card */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-gradient-to-br from-brand-600 to-brand-700 text-white rounded-3xl p-8 shadow-xl relative overflow-hidden"
      >
        <div className="absolute top-0 right-0 w-96 h-96 bg-white/5 rounded-full blur-3xl pointer-events-none" />
        <div className="flex items-center gap-3 mb-4 text-brand-100">
          <ShieldCheck className="w-6 h-6 text-emerald-400" />
          <span className="text-sm font-semibold tracking-wide uppercase">Clinical Executive Overview</span>
        </div>
        <p className="text-lg md:text-xl font-medium leading-relaxed">
          "{summaryData.executive_summary}"
        </p>
      </motion.div>

      {/* Grid of Key Sections */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Key Diagnoses */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="bg-white/70 backdrop-blur-xl border border-slate-200/60 rounded-3xl p-6 shadow-sm space-y-4"
        >
          <div className="flex items-center gap-3 pb-3 border-b border-slate-100">
            <div className="w-10 h-10 rounded-xl bg-brand-50 text-brand-600 flex items-center justify-center">
              <Activity className="w-5 h-5" />
            </div>
            <h2 className="text-lg font-bold text-slate-800">Key Diagnoses</h2>
          </div>

          {summaryData.key_diagnoses.length === 0 ? (
            <p className="text-sm text-slate-500 italic">No specific diagnoses recorded.</p>
          ) : (
            <div className="flex flex-wrap gap-2">
              {summaryData.key_diagnoses.map((d, i) => (
                <span
                  key={i}
                  className="bg-brand-50 text-brand-700 border border-brand-200 text-sm font-medium px-3 py-1.5 rounded-xl"
                >
                  {d}
                </span>
              ))}
            </div>
          )}
        </motion.div>

        {/* Clinical Recommendations */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="bg-white/70 backdrop-blur-xl border border-slate-200/60 rounded-3xl p-6 shadow-sm space-y-4"
        >
          <div className="flex items-center gap-3 pb-3 border-b border-slate-100">
            <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center">
              <Stethoscope className="w-5 h-5" />
            </div>
            <h2 className="text-lg font-bold text-slate-800">Actionable Recommendations</h2>
          </div>

          <ul className="space-y-2.5">
            {summaryData.clinical_recommendations.map((rec, i) => (
              <li key={i} className="flex items-start gap-2.5 text-sm text-slate-700 bg-slate-50 p-3 rounded-xl border border-slate-100">
                <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </motion.div>

        {/* Active Medications Summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-white/70 backdrop-blur-xl border border-slate-200/60 rounded-3xl p-6 shadow-sm space-y-4"
        >
          <div className="flex items-center gap-3 pb-3 border-b border-slate-100">
            <div className="w-10 h-10 rounded-xl bg-accent-300/20 text-accent-500 flex items-center justify-center">
              <Pill className="w-5 h-5" />
            </div>
            <h2 className="text-lg font-bold text-slate-800">Active Medications Summary</h2>
          </div>

          {summaryData.active_medications_summary.length === 0 ? (
            <p className="text-sm text-slate-500 italic">No active medications detected in uploaded reports.</p>
          ) : (
            <div className="space-y-3">
              {summaryData.active_medications_summary.map((med, i) => (
                <div key={i} className="flex items-center justify-between p-3.5 bg-white rounded-xl border border-slate-200 text-sm">
                  <div>
                    <p className="font-semibold text-slate-800">{med.name}</p>
                    <p className="text-xs text-slate-500">{med.dosage_notes || "Dosage per prescription"}</p>
                  </div>
                  <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-600 border border-emerald-200">
                    {med.status}
                  </span>
                </div>
              ))}
            </div>
          )}
        </motion.div>

        {/* Laboratory Overview */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.25 }}
          className="bg-white/70 backdrop-blur-xl border border-slate-200/60 rounded-3xl p-6 shadow-sm space-y-4"
        >
          <div className="flex items-center gap-3 pb-3 border-b border-slate-100">
            <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center">
              <Activity className="w-5 h-5" />
            </div>
            <h2 className="text-lg font-bold text-slate-800">Laboratory Overview</h2>
          </div>

          {summaryData.lab_overview.length === 0 ? (
            <p className="text-sm text-slate-500 italic">No lab findings found in uploaded reports.</p>
          ) : (
            <div className="space-y-3">
              {summaryData.lab_overview.map((lab, i) => (
                <div key={i} className="flex items-center justify-between p-3.5 bg-white rounded-xl border border-slate-200 text-sm">
                  <div>
                    <p className="font-semibold text-slate-800">{lab.test_name}</p>
                    <p className="text-xs text-slate-500">{lab.latest_finding}</p>
                  </div>
                  <span
                    className={`text-xs font-bold px-2.5 py-1 rounded-full border ${
                      lab.status === "Abnormal"
                        ? "bg-rose-50 text-rose-600 border-rose-200"
                        : "bg-emerald-50 text-emerald-600 border-emerald-200"
                    }`}
                  >
                    {lab.status}
                  </span>
                </div>
              ))}
            </div>
          )}
        </motion.div>
      </div>

      <MedicalDisclaimer />
    </div>
  );
}
